version: "2"

run:
  timeout: 5m
  tests: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable:
    # Core linters
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    
    # Security & bugs
    - gosec
    - bodyclose
    - nilerr
    - errorlint
    - noctx
    
    # Style & complexity
    - dupl
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - lll
    - misspell
    - revive
    - whitespace
    
    # Unused code
    - unparam

  settings:
    dupl:
      threshold: 150

    funlen:
      lines: 150
      statements: 80

    goconst:
      min-len: 2
      min-occurrences: 4

    gocritic:
      enabled-tags:
        - diagnostic
        - performance
      disabled-checks:
        - rangeValCopy
        - hugeParam

    gocyclo:
      min-complexity: 25

    lll:
      line-length: 240

    misspell:
      locale: US

    errcheck:
      check-type-assertions: true
      check-blank: false
      exclude-functions:
        - (io.Closer).Close
        - (sigs.k8s.io/controller-runtime/pkg/client.SubResourceWriter).Update
